Feature: Verifisere INNVFP Brev

  Scenario Outline: Verify if the INNVFP Brev meets the baseline for Scenario <Scenario> and Language <Language>
    Given we have baselines for the brevmål <BrevMål> and brevtype <BrevType> and language <Language>
    And we construct a brev xml with language <Language>
    And with behandlingsType <BehandlingsType>
    And with behandlingsResultat <BehandlingsResultat>
    And with antallBarn <Barn>
    And with relasjonskode <Relasjonskode>
    And with annenForelderHarRettVurdert <AnnenForeldreHarRettVurdert>
    And with annenForelderHarRett <AnnenForeldreHarRett>
    And with aleneomsorg <AleneOmsorg>
    And with barnErFødt <BarnErFødt>
    And with gjelderFoedsel <GjelderFødsel>
    And with fødselsHendelse <Fødselshendelse>
    And with personstatus <Personstatus>
    And with konsekvensForYtelse <KonsekvensForYtelse>
    And with dodsdato <Dodsdato>
    And with regelStatus <RegelStatus>
    And with status <Status>
    And with antallAvslag <AntallAvslag>
    And with periode 1 with årsak <Årsak1>, gradering <Gradering1> og antallTapteDager <TD1>
    And with periode 2 with årsak <Årsak2>, gradering = false og antallTapteDager <TD2>
    And with periode 3 with årsak <Årsak3>, gradering = false og antallTapteDager <TD3>
    And with periode 4 with årsak <Årsak4>, gradering = false og antallTapteDager <TD4>
    And with periode 5 with årsak <Årsak5>, gradering = false og antallTapteDager <TD5>
    And with antallArbeidsgivere <Arbeidsgivere>
    And with antallArbeidsgivereIBeregningUtenEtterlønnSluttpakke <UtenSluttpakke>
    And with etterlønnSluttpakke <EtterlønnSluttpakke>
    And with andel.dagsats <Dagsats>
    And with forMyeUtbetalt <ForMyeUtbetalt>
    And with automatiskBehandlet <AutomatiskBehandlet>
    When we generate brev based on the xml from ezbrev for the scenario <Scenario>
    Then the result brev must meet the baseline for that scenario

    @Regression
    Examples:
      | BrevMål  | BrevType | Scenario | Language | BehandlingsType | BehandlingsResultat     | KonsekvensForYtelse   | Barn |Arbeidsgivere|Relasjonskode | AnnenForeldreHarRett | AnnenForeldreHarRettVurdert | AleneOmsorg    |Fødselshendelse|BarnErFødt|GjelderFødsel|Personstatus| Dodsdato | Dagsats |UtenSluttpakke|EtterlønnSluttpakke|       RegelStatus             |        Status                |AntallAvslag| Årsak1   | Årsak2   | Årsak3   | Årsak4   | Årsak5   | TD1 | TD2 | TD3 | TD4 | TD5 |Gradering1| ForMyeUtbetalt | AutomatiskBehandlet |
      | "000061" | "INNVFP" | "SC1"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "true"               | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "2001"   | "2010"   | "2011"   | "2012"   | "2013"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC2"    | "NB"     | "REVURDERING"   | "INGEN_ENDRING"         | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC3"    | "NB"     | "REVURDERING"   | "FORELDREPENGER_ENDRET" | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "2"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC4"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "2"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "true"            | "KOMBINERT_AT_FL"             | "FRILANSER"                  | "0"        | "4095"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC5"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "2"         | "FAR"        | "true"               | "JA"                        | "NEI"          | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4503"   | "2014"   | "2020"   | "2022"   | "2021"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC6"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "JA"           | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4080"   | "2023"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC7"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "NEI"          | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "FRILANSER"                   | "FRILANSER"                  | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC8"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4504"   | "4077"   | "4020"   | "4020"   | "4005"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC9"    | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "true"               | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "5"        | "4005"   | "4003"   | "4033"   | "4041"   | "4032"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC10"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4040"   | "4039"   | "4037"   | "4037"   | "4023"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC11"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4030"   | "4038"   | "4082"   | "4025"   | "4093"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC12"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4084"   | "4086"   | "4050"   | "4051"   | "4052"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC13"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4054"   | "4055"   | "4056"   | "4057"   | "4007"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC14"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4053"   | "4008"   | "4092"   | "4002"   | "4062"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC15"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4094"   | "4074"   | "4066"   | "4013"   | "4022"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC16"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4034"   | "4035"   | "4058"   | "4060"   | "4081"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC17"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC18"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "SELVSTENDIG_NÆRINGSDRIVENDE" | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC19"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC20"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_FL_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC21"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_FL_SN"          | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC22"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "MILITÆR_ELLER_SIVIL"         | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC23"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "KUN_YTELSE"                  | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC24"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "DAGPENGER"                   | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "FERIE"       |  "false"            |
      | "000061" | "INNVFP" | "SC25"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSAVKLARINGSPENGER"     | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "GENERELL"    |  "true"             |
      | "000061" | "INNVFP" | "SC26"   | "NB"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "FRILANSER"                  | "0"        | "2038"   | "2038"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |



      | "000061" | "INNVFP" | "SC1"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "true"               | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "2001"   | "2010"   | "2011"   | "2012"   | "2013"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC2"    | "NN"     | "REVURDERING"   | "INGEN_ENDRING"         | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC3"    | "NN"     | "REVURDERING"   | "FORELDREPENGER_ENDRET" | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "2"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC4"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "2"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "true"            | "KOMBINERT_AT_FL"             | "FRILANSER"                  | "0"        | "4095"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC5"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "2"         | "FAR"        | "true"               | "JA"                        | "NEI"          | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4503"   | "2014"   | "2020"   | "2022"   | "2021"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC6"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "JA"           | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4080"   | "2023"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC7"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "NEI"          | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "FRILANSER"                   | "FRILANSER"                  | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC8"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4504"   | "4077"   | "4020"   | "4020"   | "4005"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC9"    | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "true"               | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "5"        | "4005"   | "4003"   | "4033"   | "4041"   | "4032"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC10"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4040"   | "4039"   | "4037"   | "4037"   | "4023"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC11"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4030"   | "4038"   | "4082"   | "4025"   | "4093"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC12"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4084"   | "4086"   | "4050"   | "4051"   | "4052"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC13"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4054"   | "4055"   | "4056"   | "4057"   | "4007"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC14"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4053"   | "4008"   | "4092"   | "4002"   | "4062"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC15"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4094"   | "4074"   | "4066"   | "4013"   | "4022"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC16"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4034"   | "4035"   | "4058"   | "4060"   | "4081"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC17"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC18"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "SELVSTENDIG_NÆRINGSDRIVENDE" | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC19"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC20"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_FL_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC21"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_FL_SN"          | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC22"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "MILITÆR_ELLER_SIVIL"         | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC23"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "KUN_YTELSE"                  | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC24"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "DAGPENGER"                   | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "FERIE"       |  "false"            |
      | "000061" | "INNVFP" | "SC25"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSAVKLARINGSPENGER"     | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "GENERELL"    |  "true"             |
      | "000061" | "INNVFP" | "SC26"   | "NN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "FRILANSER"                  | "0"        | "2038"   | "2038"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |



      | "000061" | "INNVFP" | "SC1"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "true"               | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "2001"   | "2010"   | "2011"   | "2012"   | "2013"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC2"    | "EN"     | "REVURDERING"   | "INGEN_ENDRING"         | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC3"    | "EN"     | "REVURDERING"   | "FORELDREPENGER_ENDRET" | "ENDRING_I_BEREGNING" | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "true"   | "2304"  | "2"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC4"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "2"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "true"            | "KOMBINERT_AT_FL"             | "FRILANSER"                  | "0"        | "4095"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC5"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "2"         | "FAR"        | "true"               | "JA"                        | "NEI"          | "false"       | "false"  | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4503"   | "2014"   | "2020"   | "2022"   | "2021"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC6"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "JA"           | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "0"        | "4080"   | "2023"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC7"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "IKKE_VURDERT"              | "NEI"          | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "FRILANSER"                   | "FRILANSER"                  | "0"        | "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC8"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "false"              | "NEI"                       | "JA"           | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4504"   | "4077"   | "4020"   | "4020"   | "4005"   | "1" | "1" | "2" | "1" | "1" | "true"   |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC9"    | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "true"               | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "5"        | "4005"   | "4003"   | "4033"   | "4041"   | "4032"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC10"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4040"   | "4039"   | "4037"   | "4037"   | "4023"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC11"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4030"   | "4038"   | "4082"   | "4025"   | "4093"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC12"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4084"   | "4086"   | "4050"   | "4051"   | "4052"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC13"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4054"   | "4055"   | "4056"   | "4057"   | "4007"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC14"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4053"   | "4008"   | "4092"   | "4002"   | "4062"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC15"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4094"   | "4074"   | "4066"   | "4013"   | "4022"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC16"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "false"       | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4034"   | "4035"   | "4058"   | "4060"   | "4081"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC17"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC18"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "SELVSTENDIG_NÆRINGSDRIVENDE" | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC19"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC20"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_FL_SN"             | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC21"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "0"     | "1"          | "false"           | "KOMBINERT_AT_FL_SN"          | "SELVSTENDIG_NÆRINGSDRIVENDE"| "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |
      | "000061" | "INNVFP" | "SC22"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "MILITÆR_ELLER_SIVIL"         | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC23"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "KUN_YTELSE"                  | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "false"            |
      | "000061" | "INNVFP" | "SC24"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "DAGPENGER"                   | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "FERIE"       |  "false"            |
      | "000061" | "INNVFP" | "SC25"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_BEREGNING" | "2"  | "1"         | "MOR"        | "DEFAULT"            | "JA"                        | "NEI"          | "true"        | "true"   | "false"     | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSAVKLARINGSPENGER"     | "ARBEIDSTAKER"               | "4"        | "4100"   | "4073"   | "4075"   | "4087"   | "2001"   | "1" | "1" | "2" | "1" | "1" | "false"  |  "GENERELL"    |  "true"             |
      | "000061" | "INNVFP" | "SC26"   | "EN"     | "REVURDERING"   | "INNVILGET"             | "ENDRING_I_UTTAK"     | "1"  | "1"         | "FAR"        | "DEFAULT"            | "IKKE_VURDERT"              | "IKKE_VURDERT" | "false"       | "true"   | "true"      | "ANNET"    | "false"  | "2304"  | "1"          | "false"           | "ARBEIDSTAKER"                | "FRILANSER"                  | "0"        | "2038"   | "2038"   | "DEFAULT"| "DEFAULT"| "DEFAULT"| "1" | "1" | "2" | "1" | "1" | "false"  |  "INGEN"       |  "true"             |


